server:
  port: 8000
 
spring:
    application:
      name: address-service
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://db-mysql-lon1-75379-do-user-19481328-0.d.db.ondigitalocean.com:25060/address-service
        username: "address-service"
        password: "AVNS_lSEEGO06XE8vLKQ9BpJ"
        hikari:
            initialization-fail-timeout: 0  
    sql:
        int:
          platform: mysql
          mode: always        
    jpa:
        databasePlatform: "org.hibernate.dialect.MySQLDialect"
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
